version: 3

env:
  DOCKER_IMAGE_NAME: 4lch4/notigate
  DOCKER_TAG: latest
  DOCKER_IMAGE: ${DOCKER_IMAGE_NAME}:${DOCKER_TAG}
  CONTAINER_NAME: notigate
  API_PORT: 4242

tasks:
  pretty:
    desc: Uses the Prettier CLI tool to format the codebase.
    aliases: [p, format, fmt]
    cmd: prettier --write .

  build:
    desc: Builds the project into a Docker image for use on the local architecture.
    aliases: [b]
    cmd: docker build -t ${DOCKER_IMAGE} .

  clean:
    desc: Deletes the build output directory, any installed dependencies, any generated files, and any built Docker images.
    aliases: [c]
    cmds:
      - rm -rf dist node_modules package-lock.json bun.lockb
      - docker rm ${CONTAINER_NAME}

  start:
    desc: Starts the project locally in a Docker container.
    aliases: [s, up]
    cmd: docker run -d -p ${API_PORT}:${API_PORT} --env-file=.env --name ${CONTAINER_NAME} ${DOCKER_IMAGE}

  stop:
    desc: Stops the locally running Docker container.
    aliases: [st, down]
    cmd: docker stop ${CONTAINER_NAME}

  logs:
    desc: Tails the logs of the locally running Docker container.
    aliases: [l]
    cmd: docker logs -f ${CONTAINER_NAME}

  restart:
    desc: Rebuilds, stops, deletes, and starts the locally running Docker container.
    aliases: [r, reboot]
    cmds:
      - task build
      - task stop
      - task clean
      - task start

  push:
    desc: Push any git changes and tags to the remote repository.
    aliases: [gp]
    cmds:
      - git push
      - git push --tags
